joint_limits:
  ${name}_joint1:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint2:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint3:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint4:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint5:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint6:
    has_acceleration_limits: true
    max_acceleration: 5.0
  ${name}_joint7:
    has_acceleration_limits: true
    max_acceleration: 5.0
