# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - ${controller_name}_controller

  ${controller_name}_controller:
    type: GripperCommand
    joints:
      - ${name}_finger_joint1
      - ${name}_finger_joint2
    action_ns: gripper_action
    default: true
