<?xml version="1.0"?>
<robot name="j100"
  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="is_sim" default="false" />
  <xacro:arg name="prefix" default="" />
  <xacro:arg name="namespace" default="" />
  <xacro:arg name="gazebo_controllers" default="$(find clearpath_control)/config/j100/control.yaml"/>
  <xacro:arg name="use_platform_controllers" default="true"/>

  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.0345" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" />
  <xacro:property name="chassis_height" value="0.184" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <xacro:macro name="j100" params="control:='diff_fwd' front_wheels:='outdoor' rear_wheels:='outdoor'">
    <link name="base_link"></link>

    <joint name="base_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="chassis_link" />
    </joint>

    <link name="chassis_link">
      <visual>
        <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <mesh filename="package://clearpath_platform_description/meshes/j100/j100_base.stl"/>
        </geometry>
        <material name="clearpath_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${chassis_height/2}"/>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
        <mass value="16.523"/>
        <inertia ixx="0.3136" ixy="-0.0008" ixz="0.0164" iyy="0.3922" iyz="-0.0009" izz="0.4485"/>
      </inertial>
    </link>

    <!-- Add wheels -->
    <xacro:include filename="$(find clearpath_platform_description)/urdf/j100/drivetrain/wheels.urdf.xacro"/>
    <xacro:j100_drivetrain_wheels front_wheels="${front_wheels}" rear_wheels="${rear_wheels}"/>

    <!-- Add drivetrain -->
    <xacro:include filename="$(find clearpath_platform_description)/urdf/generic/drivetrain/drivetrain.urdf.xacro"/>

    <!-- Hardware  -->
    <xacro:if value="$(arg is_sim)">
      <xacro:property name="hardware_plugin" value="gz_ros2_control/GazeboSimSystem"/>
    </xacro:if>
    <xacro:unless value="$(arg is_sim)">
      <xacro:property name="hardware_plugin" value="clearpath_hardware_interfaces/J100Hardware"/>
    </xacro:unless>

    <xacro:if value="$(arg use_platform_controllers)">
      <xacro:generic_drivetrain
        name="j100"
        control="${control}"
        front_wheels="${front_wheels}"
        rear_wheels="${rear_wheels}"
        hardware_plugin="${hardware_plugin}"
      />
    </xacro:if>

    <link name="imu_0_link">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
      </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent link="chassis_link" />
      <child link="imu_0_link" />
    </joint>

    <gazebo reference="imu_0_link">
      <sensor type="imu" name="imu_0">
        <always_on>true</always_on>
        <update_rate>50</update_rate>
        <visualize>true</visualize>
        <gz_frame_id>imu_0_link</gz_frame_id>
        <topic>$(arg namespace)/sensors/imu_0/data_raw</topic>
      </sensor>
    </gazebo>

    <link name="gps_0_link">
      <visual>
        <geometry>
          <cylinder radius="0.026" length="0.016" />
        </geometry>
        <origin xyz="0 0 0.008" />
        <material name="clearpath_black" />
      </visual>
    </link>
    <joint name="navsat_joint" type="fixed">
      <parent link="chassis_link" />
      <child link="gps_0_link" />
      <origin xyz="-0.180 0.126 0.1815" />
    </joint>

    <gazebo reference="gps_0_link">
      <sensor name="gps_0" type="navsat">
        <always_on>1</always_on>
        <update_rate>10</update_rate>
        <gz_frame_id>gps_0_link</gz_frame_id>
        <topic>$(arg namespace)/sensors/gps_0/navsat</topic>
      </sensor>
    </gazebo>

    <link name="default_mount"></link>
    <joint name="default_mount_joint" type="fixed">
      <parent link="chassis_link" />
      <child link="default_mount" />
      <origin xyz="0 0 ${chassis_height}" />
    </joint>

    <link name="rear_0_mount"></link>
    <joint name="rear_0_mount_joint" type="fixed">
      <parent link="default_mount" />
      <child link="rear_0_mount" />
      <origin xyz="${-mount_spacing} 0 0" />
    </joint>

    <link name="front_0_mount"></link>
    <joint name="front_0_mount_joint" type="fixed">
      <parent link="default_mount" />
      <child link="front_0_mount" />
      <origin xyz="${mount_spacing} 0 0" />
    </joint>
  </xacro:macro>
</robot>
